# Generated by Django 4.0 on 2021-12-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='senha',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
