# Generated by Django 4.0 on 2021-12-17 23:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('especializacao', '0001_initial'),
        ('perfil', '0003_remove_perfil_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='especializacao',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='especializacao.especializacao'),
        ),
    ]
