# Generated by Django 4.0 on 2021-12-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_perfil_data_criacao_alter_perfil_especializacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(default='perfil/utils/default-image-auxiliar-ensino.png', upload_to='perfil/%Y/%m'),
        ),
    ]
