# Generated by Django 4.0 on 2021-12-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_alter_perfil_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='slug',
            field=models.SlugField(default=None),
        ),
    ]
