# Generated by Django 4.0 on 2021-12-17 23:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0004_perfil_data_criacao_alter_perfil_especializacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(default=0)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('serie', models.CharField(blank=True, max_length=10, null=True)),
                ('recuperacao', models.BooleanField(default=False)),
                ('publico', models.BooleanField(default=False)),
                ('teste_texto', ckeditor.fields.RichTextField()),
                ('perfil_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil')),
            ],
        ),
    ]
