# Generated by Django 4.0 on 2021-12-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='nome_prova',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
