# Generated by Django 4.0 on 2021-12-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0002_prova_nome_prova'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='slug',
            field=models.SlugField(default=None),
        ),
    ]
