# Generated by Django 4.0 on 2021-12-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0003_prova_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
